### ISSUE TITLE
Tmux doesn't resize to follow terminal window size when launched from twm

### ISSUE THREAD

**Issue by tombuntus** [vinnymeller/twm#16]
When I launch tmux normally with `$ tmux` then resize the terminal window, the tmux window resizes as you would expect.

When I launch tmux via twm with `$ twm` then resize the terminal window, the tmux window does not resize/redraw. I'd appreciate any help or pointers.

twm version: 0.8.0
tmux version: next-3.4

I normally use Alacritty (v0.12.3), but have tried gnome terminal and Xterm too. Same behaviour.

EDIT: If I launch tmux first with `$ tmux` and then `:run-shell "tmux neww twm"` the resize behaviour works as expected.

Thanks.

**Comment by vinnymeller** [comment]
holy crap this has annoyed me for so long, i never even considered that it was an issue only when starting through twm.

I also get the correct resizing behavior just running `tmux` first. I also get correct resizing if I launch tmux with `twm`, detach, and attach back to the twm-generated session.

i will definitely investigate this

**Comment by vinnymeller** [comment]
@tombuntus are you able to check if 0.9.0 works as expected for you? i tested on as many systems and shells & terminals as I have, and so far working on all  :smile:

**Comment by tombuntus** [comment]
> holy crap this has annoyed me for so long

It took me a long time and lots of frustrated time sifting through stackoverflow and github issues to realise it wasn't an issue with the terminal emulator or tmux!

> @tombuntus are you able to check if 0.9.0 works as expected for you? i tested on as many systems and shells & terminals as I have, and so far working on all 😄

Works for me :+1:
