### ISSUE TITLE
attach new session in group

### ISSUE THREAD

**Issue by tombuntus** [vinnymeller/twm#19]
With tmux you can create a new session and attach it to an existing session in a group. Both sessions share the same windows and panes but you can view a different window concurrently in each session:

`$ tmux new-session -t existing-session-name`

This is really useful when trying to put different windows from the same session on different physical screens.

It would be nice to be able to do to something like `$ twm -g`, fuzzy find over workspaces, select one and have it create a new session grouped with an existing session in the same workspace instead of just attaching to the existing session.

**Comment by vinnymeller** [comment]
@tombuntus i've made quite a few changes on the `development` branch, but thought you'd possibly want to try it out

in that  build you can press `Ctrl+Enter` / `Shift+Enter` / `Alt+Enter` to _attempt_ to open a workspace selected in the standard finder (e.g. just running `twm`)

it basically goes:
  - if `*modifier* + enter`:
    - try finding a twm-generated session with the same path as the workspace you selected (based on auto-set `TWM_ROOT` env var)
    - if one is found, create a new session in a group as if you used `twm -g` and selected the matching session
    - if none found, move on
- open the workspace as is normally expected with just `enter`   

the reason all 3 combinations of `ctrl+enter` / `shift+enter` / `alt+enter` do the same thing currently is that it seems only `alt+enter` (consistently?) works on linux with the `crossterm` library, but from what I've seen the other's might work on windows/mac
